apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailsender
spec:
  # replicaset: 1
  selector:
    matchLabels:
      app: mailsender
  template:
    metadata:
      labels:
        app: mailsender
    spec:
      containers:
      - name: mailsender
        image: sakthisaransss55/mailsender:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mailsenderservice
spec:
  selector:
    app: mailsender
  ports:
  - port: 80
    targetPort: 80

